### ISSUE TITLE
Ring fence SQLAlchemy

### ISSUE THREAD

**Issue by jdkandersson** [jdkandersson/OpenAlchemy#29]
As a developer I want to limit my dependency on SQLAlchemy so that the logic can be used for other types of ORMs in the future.

At the moment references to SQLAlchemy are present throughout the code. This would make it difficult to add support for things like Django ORM in the future. Expose the types of functionality required for an ORM through a separate interface and make SQLALchemy one of the implementers of the interface.

**Comment by xem-zenhub** [comment]
Hola!

Wondering what happened with this enhancement and if there are any examples of plugging into Django??

I have this specific need. I wrote a schema first microservice factory, and now a client wants to use it but use Django ORM rather than SQLAlchemy...I just can't see myself handcrafting all those classes when they could be generated!

Thanks in advance....

**Comment by jdkandersson** [comment]
Django is not currently supported, it would be quite a bit of work and it is unlikely to happen soon without someone's help
