### ISSUE TITLE
Multiple classes found for path "Division" in the registry of this declarative base. Please use a fully module-qualified path.

### ISSUE THREAD

**Issue by alex-bezverkhniy** [jdkandersson/OpenAlchemy#90]
Hello,
I really like the idea and simplicity of this framework! Thank you for your work! it works well with simple model (from the example) but when I add **Many to One** (base on your [documentation](https://openapi-sqlalchemy.readthedocs.io/en/latest/technical_details/relationships.html#many-to-one)) relationship I faced with an exception when I am trying *query* data from DB:

> sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "Division" in the registry of this declarative base. Please use a fully module-qualified path.

Here is en example of OpenAPI spec:
```yaml
openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate OpenAlchemy.
  version: "1.0"

paths:
  /division:
    get:
      operationId: api.search_divisions
      summary: Used to retrieve all divisions.
      responses:
        200:
          description: Return all divisions from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Division"
    post:
      operationId: api.post_division
      summary: Used to save an division to the database.
      requestBody:
        description: The division to save.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Division"
      responses:
        200:
          description: Save successful.
        400:
          description: The Division already exists.

  /employee:
    get:
      operationId: api.search
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      operationId: api.post
      summary: Used to save an employee to the database.
      requestBody:
        description: The employee to save.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        200:
          description: Save successful.
        400:
          description: The Employee already exists.
components:
  schemas:
    Division:
      description: A part of a company.
      type: object
      x-tablename: division
      properties:
        id:
          type: integer
          description: Unique identifier for the division.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the division.
          example: Engineering
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
        division:
          "$ref": "#/components/schemas/Division"                        
      required:
        - id
        - name
```
So actually I use [your example app](url) and I just added new type `Division` and reference to it.
```yaml        
division:
          "$ref": "#/components/schemas/Division" 
```

**Comment by alex-bezverkhniy** [comment]
I found solution!
I have to import all models directly from `open_alchemy.models`. Do not import it from auto generated module `import models_autogenerated as models`.
e.g:
```python
from open_alchemy.models import Employee, Division
...
# And then use
employees = Employee.query.all()
...
```

**Comment by jdkandersson** [comment]
Thank you for reporting this! I'm glad you found a work around.

There is actually a real bug here. The problem is that, the way the auto generated files are done, it causes another class to be registered under the same name in the internal SQLAlchemy class registry.

Currently the options are:
1. Change the name of the class in the auto generated models (easiest but user impacting)
2. Change the internal name of the model class generated y open_alchemy without changing the name it is registered on the open_alchemy.models module (clunky but not user impacting)
3. Find an alternative way of creating the auto generated models without registering another SQLAlchemy model (preferred, most complex)

The file `./sqlalchemy/ext/declarative/clsregistry.py` is helpful as it is obvious under what name the model is registered.

**Comment by jdkandersson** [comment]
Your reporting of this bug has had quite a positive effect on this package. It has resulted in the following changes:

1. the bug was fixed so that others don't encounter the same bug again,
2. the way auto generating models works has been changed to remove class inheritance which has a special meaning within SQLAlchemy I was not previously aware of and
3. the production use of the auto generated models file has been sped up as the _\_\_init\_\__, _from_dict_ and _to_dict_ functions are not longer intercepted.
