### ISSUE TITLE
Support for $ref Remote Reference 

### ISSUE THREAD

**Issue by anovis** [jdkandersson/OpenAlchemy#99]
https://swagger.io/docs/specification/using-ref/

Remote Reference –  $ref: 'document.json' Uses the whole document located on the same server and in the same location.

```
The element of the document located on the same server – $ref: 'document.json#/myElement'
The element of the document located in the parent folder – $ref: '../document.json#/myElement'
The element of the document located in another folder – $ref: '../another-folder/document.json#/myElement'
```

https://github.com/jdkandersson/OpenAlchemy/blob/11dcc1ef703a6c69427bff9848357b8ca33c1529/open_alchemy/helpers/resolve_ref.py#L45

**Comment by jdkandersson** [comment]
An additional possibility is that the _$ref_ starts with a URI. This is out of scope for this feature request and will be looked at after remote references within the file system have been implemented.

The proposal is to look for any _$ref_ that don't start with _#_ and treat them in a special way. The main difficulty is any _$ref_  within a remote reference as that would need to be resolved within the context of the remote reference. The options to deal with this is:

1. resolve any _$ref_ within the remote reference before returning it
2. re-write any _$ref_ within the remote reference to reflect the context
3. wrap the return value in a special object that retains the remote context

(3) would be quite complex because there is no certainty at what depth the reference may be. (1) may waste compute resource on resolving _$ref_ which are never used in practice. (2) is feasible and would require compute and memory on the same order as is required to resolve the remote reference to begin with.

The proposed implementation of (2) is to serialise the dictionary before returning it, do a pattern match for _$ref_, update it according to the below rules and then de-serialise it again.

1. If it starts with _#_, prepend the reference with the context (eg. if it occurs within "document.json" the _$ref_ becomes "document.json#...".
2. If it starts with another document, merge the context of the document context to generate the new context and update the value before _#_.

An additional complexity is that there is a requirement to know the absolute file path of the initial OpenAPI specification. This is only possible in the case where _init_yaml_ or _init_json_ have been used. An optional parameter is to be added to _init_model_factory_ to record the absolute path. This needs to be stored in configuration so that it can be retrieved. The proposal is to put that configuration within the same context as _get_ref_.

To limit the number of disk accesses, the de-serialised schema is to be stored with its context in memory.
